stages:
  - build
  - publish

build:
  image: node:lts-slim
  stage: build
  only:
    - master
  before_script:
    - npm ci
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - .npm-cache/
  artifacts:
    paths:
      - dist/
  script:
    - npm run build

publish:
  image: mcr.microsoft.com/azure-cli
  stage: publish
  needs: ["build"]
  variables:
    AZURE_SAS: $AZURE_SAS
  only:
    - master
  script:
    - az storage blob delete-batch --account-name pmatarnold --sas-token $AZURE_SAS --source '$web'
    - az storage blob upload-batch --destination '$web' --account-name pmatarnold --sas-token $AZURE_SAS --destination-path / --source ./dist/
